services:
  app:
    container_name: mephi-db-seeder
    restart: no
    profiles: [ seed ]
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DSN: "host=mephi-db user=mephi password=mephi dbname=mephi-db port=5432 sslmode=disable TimeZone=Europe/Moscow"

  hw:
    container_name: mephi-db-hw
    restart: no
    profiles: [ hw ]
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile.hw
    environment:
      DSN: "host=mephi-db user=mephi password=mephi dbname=mephi-db port=5432 sslmode=disable TimeZone=Europe/Moscow"

  database:
    container_name: mephi-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: mephi
      POSTGRES_USER: mephi
      POSTGRES_DB: mephi-db
    ports:
      - 5432:5432
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    command: >
      -c work_mem=256MB -c maintenance_work_mem=256MB -c max_wal_size=10GB -c max_connections=500
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10

  pgadmin:
    container_name: mephi-pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: mephi@localhost.ru
      PGADMIN_DEFAULT_PASSWORD: mephi
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      GUNICORN_ACCESS_LOGFILE: /dev/null
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
